TST: attempt to fix pytest build
why's it failing on just the python 3.6 build? i'm getting
the following error message -

_____________________ ERROR collecting strainflye/_cli.py ______________________
strainflye/_cli.py:1164: in <module>
    exists=True, file_okay=True, dir_okay=False, executable=True
E   TypeError: __init__() got an unexpected keyword argument 'executable'

presumably this is due to me telling pytest to look not just in
strainflye/tests -- this way, pytest can find doctests.

if needed i can ditch doctests (or ditch py 3.6 support) but i would
prefer not to